<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>dotnet-Vegetable.Workers-52BA9994-E0B6-4F2D-A22B-8A119FD40487</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Vegetable.API\appsettings.Development.json" Link="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Vegetable.API\appsettings.json" Link="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Vegetable.API\appsettings.Local.json" Link="appsettings.Local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Vegetable.API\appsettings.Production.json" Link="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.4" />
    <PackageReference Include="Telegram.Bot" Version="17.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vegetable.Core\Vegetable.Core.csproj" />
  </ItemGroup>
</Project>
